In [196]:
import pandas as pd 
import numpy as np 

# Defining Neural Network 

# Iam using 2 hidden layers between input layer and output layer.There are 3 input columns and a output column. 

# Taking 4 nodes on first layer and 2 nodes on the second layer. 

In [197]:
np.random.seed(42)
X = np.random.randn(5, 3)
y = np.random.randint(0, 2, size=(5, 1)) 

In [198]:
X 

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [199]:
y 

array([[0],
       [0],
       [1],
       [1],
       [1]], dtype=int32)

In [200]:
input_columns=3
hidden1=4
hidden2=2
output=1

# Defining  Sigmoid Function 

In [201]:
def sigmoid(z): 
    return 1/(1+np.exp(-z))

# For the first hidden Layer 

In [202]:
np.random.seed(42)
w1=np.random.randn(input_columns,hidden1)*0.4
b1=np.random.randn(1,hidden1)
w1 

array([[ 0.19868566, -0.05530572,  0.25907542,  0.60921194],
       [-0.09366135, -0.09365478,  0.63168513,  0.30697389],
       [-0.18778975,  0.21702402, -0.18536708, -0.1862919 ]])

In [203]:
w1.shape

(3, 4)

In [204]:
b1 

array([[ 0.24196227, -1.91328024, -1.72491783, -0.56228753]])

In [205]:
b1.shape

(1, 4)

In [206]:
X.shape

(5, 3)

In [207]:
dot_hidden1=np.dot(X,w1)

In [208]:
dot_hidden1.shape

(5, 4)

In [209]:
output_hidden1=dot_hidden1+b1

In [210]:
output_hidden1_acf=sigmoid(output_hidden1)

In [211]:
output_hidden1_acf.shape

(5, 4)

# Now Output From Hidden 1 becomes input to the hidden layer 2 

In [212]:
input_hidden2=output_hidden1_acf

In [213]:
input_hidden2.shape

(5, 4)

In [214]:
output_hidden1_acf

array([[0.55773458, 0.14341165, 0.14140964, 0.39585028],
       [0.64804712, 0.11645922, 0.19234441, 0.58353434],
       [0.63922747, 0.1020748 , 0.32213435, 0.67322978],
       [0.6178954 , 0.11910215, 0.14297994, 0.42867751],
       [0.68850923, 0.10699378, 0.07235403, 0.33606714]])

# weights and biases for the hidden layer 2  

In [215]:
w2=np.random.randn(hidden1,hidden2)*0.4
b2=np.random.randn(1,hidden2)
w2 

array([[-0.40513245,  0.12569893],
       [-0.36320963, -0.56492148],
       [ 0.58625951, -0.09031052],
       [ 0.02701128, -0.56989927]])

In [216]:
dot_hidden2=np.dot(output_hidden1_acf,w2)
output_hidden2=dot_hidden2+b2

In [217]:
output_hidden2_acf=sigmoid(output_hidden2)
output_hidden2_acf

array([[0.325451  , 0.4654669 ],
       [0.32723864, 0.44439707],
       [0.34674228, 0.43066053],
       [0.32244268, 0.46607531],
       [0.30774444, 0.48474614]])

In [218]:
input_output_layer=output_hidden2_acf

In [219]:
input_output_layer.shape

(5, 2)

In [220]:
w3=np.random.randn(hidden2,output)*0.4
b3=np.random.randn(1,output)
w3 

array([[-0.46039743],
       [ 0.15027921]])

In [224]:
dot_hidden3=np.dot(input_output_layer,w3)
output_output_layer=dot_hidden3+b3
output_output_layer_acf=sigmoid(output_output_layer)
output_output_layer_acf

array([[0.33614403],
       [0.33525437],
       [0.33279767],
       [0.33647358],
       [0.33861414]])

In [227]:
def output_classify(num): 
    if num >0.334:
        return 1 
    else:  return 0

In [229]:
output_classify_vec = np.vectorize(output_classify)

output_classify_vec(output_output_layer_acf)

array([[1],
       [1],
       [0],
       [1],
       [1]])