In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [ ]:
x=load_iris().data
y=load_iris().target

In [ ]:
x.shape

(150, 4)

In [ ]:
y.shape

(150,)

In [ ]:
type(y)

numpy.ndarray

In [31]:
# Architecture: 4 (input) -> 2 (hidden1) -> 2 (hidden2) -> 1 (output)

In [ ]:
import numpy as np

def initialize_parameters():

    params = {
        'W1': np.random.randn(2, 4) * 0.01,
        'b1': np.zeros((2, 1)),
        'W2': np.random.randn(2, 2) * 0.01,
        'b2': np.zeros((2, 1)),
        'W3': np.random.randn(1, 2) * 0.01,
        'b3': np.zeros((1, 1))
    }
    return params

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def forward_propagation(X, params):
    # Layer 1
    Z1 = np.dot(params['W1'], X) + params['b1']
    A1 = np.tanh(Z1)
    # Layer 2
    Z2 = np.dot(params['W2'], A1) + params['b2']
    A2 = np.tanh(Z2)
    # Layer 3 (Output)
    Z3 = np.dot(params['W3'], A2) + params['b3']
    A3 = sigmoid(Z3)

    cache = {"Z1": Z1, "A1": A1, "Z2": Z2, "A2": A2, "Z3": Z3, "A3": A3}
    return A3, cache

def back_propagation(X, Y, cache, params):
    m = X.shape[1]

    # Output layer
    dZ3 = cache['A3'] - Y
    dW3 = (1/m) * np.dot(dZ3, cache['A2'].T)
    db3 = (1/m) * np.sum(dZ3, axis=1, keepdims=True)

    # Hidden layer 2
    dA2 = np.dot(params['W3'].T, dZ3)
    dZ2 = dA2 * (1 - np.power(cache['A2'], 2))
    dW2 = (1/m) * np.dot(dZ2, cache['A1'].T)
    db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)

    # Hidden layer 1
    dA1 = np.dot(params['W2'].T, dZ2)
    dZ1 = dA1 * (1 - np.power(cache['A1'], 2))
    dW1 = (1/m) * np.dot(dZ1, X.T)
    db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

    grads = {"dW1": dW1, "db1": db1, "dW2": dW2, "db2": db2, "dW3": dW3, "db3": db3}
    return grads

def update_parameters(params, grads, learning_rate=0.01):
    params['W1'] -= learning_rate * grads['dW1']
    params['b1'] -= learning_rate * grads['db1']
    params['W2'] -= learning_rate * grads['dW2']
    params['b2'] -= learning_rate * grads['db2']
    params['W3'] -= learning_rate * grads['dW3']
    params['b3'] -= learning_rate * grads['db3']
    return params

In [ ]:
A3

array([[0.95148108, 0.94814839, 0.95017947, 0.94661849, 0.95173454,
        0.95097259, 0.94980822, 0.95006577, 0.94537938, 0.94822353,
        0.95199384, 0.94852332, 0.94844196, 0.9504817 , 0.95389288,
        0.9535425 , 0.9530251 , 0.95119368, 0.95128147, 0.95174923,
        0.94883874, 0.95106322, 0.95313104, 0.94467542, 0.94297387,
        0.9451334 , 0.94792971, 0.95093521, 0.95120583, 0.94632731,
        0.9455494 , 0.95004135, 0.95306707, 0.95359159, 0.94761707,
        0.95142921, 0.95246586, 0.95186231, 0.94808485, 0.95025593,
        0.95170174, 0.93629802, 0.94957158, 0.94758357, 0.94750162,
        0.94721324, 0.95139795, 0.94893034, 0.95187905, 0.95040146,
        0.02167883, 0.02184292, 0.02046997, 0.02109089, 0.02054872,
        0.02060177, 0.02094887, 0.02938337, 0.02110895, 0.02231969,
        0.02300444, 0.02225879, 0.02188897, 0.02034639, 0.03016151,
        0.02276576, 0.0206529 , 0.02303886, 0.0198528 , 0.02295922,
        0.02007408, 0.02391933, 0.01960787, 0.02

In [34]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [33]:
X_data

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [35]:
X_data.shape

(4, 150)

In [ ]:
#Applying Batch Gradient Descent in Backpropagation

In [37]:
A3.shape

(1, 150)

In [ ]:

X_data = x.T
Y_data = (y == 0).reshape(1, -1)

parameters = initialize_parameters()
epochs = 1000
learning_rate = 0.1
total_cost=0
epoch_cost=0

for i in range(epochs):
    # Forward
    A3, cache = forward_propagation(X_data, parameters)

    # Cost (Binary Cross Entropy)
    cost = -np.mean(Y_data * np.log(A3) + (1 - Y_data) * np.log(1 - A3))

    # Backward
    grads = back_propagation(X_data, Y_data, cache, parameters)

    # Update
    parameters = update_parameters(parameters, grads, learning_rate)
    cost = -np.mean(Y_data * np.log(A3 + 1e-8) + (1 - Y_data) * np.log(1 - A3 + 1e-8))
    epoch_cost += cost
    total_cost+=cost


    if i % 100 == 0:
        print(f"Epoch {i}, Avg Epoch Cost: {epoch_cost / X_data.shape[0]}")
print(f'Total Cost is {total_cost}')
print(f"Epoch {i}, Avg Total Cost: {total_cost / (X_data.shape[0]*epochs)}")


Epoch 0, Avg Epoch Cost: 0.0
Epoch 100, Avg Epoch Cost: 0.0
Epoch 200, Avg Epoch Cost: 0.0
Epoch 300, Avg Epoch Cost: 0.0
Epoch 400, Avg Epoch Cost: 0.0
Epoch 500, Avg Epoch Cost: 0.0
Epoch 600, Avg Epoch Cost: 0.0
Epoch 700, Avg Epoch Cost: 0.0
Epoch 800, Avg Epoch Cost: 0.0
Epoch 900, Avg Epoch Cost: 0.0
Total Cost is 0
Epoch 999, Avg Total Cost: 0.0


In [ ]:
#Applying Stochastic Gradient Descent

In [ ]:
X_data=x

X_data[1].reshape(-1,1)

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

In [ ]:
y[1].reshape(1,1)

array([[0]])

In [ ]:
X_data = x
Y_data = (y == 0).astype(int)

parameters = initialize_parameters()
epochs = 1000
learning_rate = 0.01
total_cost=0
for i in range(epochs):
    epoch_cost = 0
    num2=num1
    num1+=50
    for j in range(X_data.shape[0]):
      xj = X_data[j].reshape(-1, 1)
      yj = Y_data[j].reshape(1, 1)

      # Forward
      A3, cache = forward_propagation(xj, parameters)

      # Backward
      grads = back_propagation(xj, yj, cache, parameters)

      # Update
      parameters = update_parameters(parameters, grads, learning_rate)

      cost = -np.mean(yj * np.log(A3 + 1e-8) + (1 - yj) * np.log(1 - A3 + 1e-8))
      epoch_cost += cost
      total_cost+=cost

    if i % 100 == 0:
        print(f"Epoch {i}, Avg Epoch Cost: {epoch_cost / X_data.shape[0]}")
print(f'Total Cost is {total_cost}')
print(f"Epoch {i}, Avg Total Cost: {total_cost / (X_data.shape[0]*epochs)}")


Epoch 0, Avg Epoch Cost: 0.6693505527607357
Epoch 100, Avg Epoch Cost: 0.007968748513635354
Epoch 200, Avg Epoch Cost: 0.0023546727680609615
Epoch 300, Avg Epoch Cost: 0.001380124157187147
Epoch 400, Avg Epoch Cost: 0.0009759852482637444
Epoch 500, Avg Epoch Cost: 0.0007548885562641399
Epoch 600, Avg Epoch Cost: 0.0006154517614118787
Epoch 700, Avg Epoch Cost: 0.0005194901336865666
Epoch 800, Avg Epoch Cost: 0.0004494145171671137
Epoch 900, Avg Epoch Cost: 0.0003959960561122477
Total Cost is 5741.573567562403
Epoch 999, Avg Total Cost: 0.03827715711708268


Mini Batch Gradient Descent


In [ ]:
X_data = x
Y_data = (y == 0).astype(int)

parameters = initialize_parameters()
epochs = 1000
learning_rate = 0.01
total_cost=0
batch_size=50
for i in range(epochs):
    epoch_cost = 0
    num1=0
    num2=0
    while num1<=X_data.shape[0] and (X_data.shape[0]-num2)!=batch_size:
      num2=num1
      num1+=batch_size

      for j in range(num2,num1):
        xj = X_data[j].reshape(-1, 1)
        yj = Y_data[j].reshape(1, 1)

        # Forward
        A3, cache = forward_propagation(xj, parameters)

        # Backward
        grads = back_propagation(xj, yj, cache, parameters)

        # Update
        parameters = update_parameters(parameters, grads, learning_rate)

        cost = -np.mean(yj * np.log(A3 + 1e-8) + (1 - yj) * np.log(1 - A3 + 1e-8))
        epoch_cost += cost
        total_cost+=cost

    if i % 100 == 0:
        print(f"Epoch {i}, Avg Epoch Cost: {epoch_cost / X_data.shape[0]}")
print(f'Total Cost is {total_cost}')
print(f"Epoch {i}, Avg Total Cost: {total_cost / (X_data.shape[0]*epochs)}")


Epoch 0, Avg Epoch Cost: 0.669356976837216
Epoch 100, Avg Epoch Cost: 0.6364200356898346
Epoch 200, Avg Epoch Cost: 0.004061160264169182
Epoch 300, Avg Epoch Cost: 0.0018280724883185228
Epoch 400, Avg Epoch Cost: 0.001179496024472462
Epoch 500, Avg Epoch Cost: 0.0008706452097035303
Epoch 600, Avg Epoch Cost: 0.0006899938639448273
Epoch 700, Avg Epoch Cost: 0.0005714383024072775
Epoch 800, Avg Epoch Cost: 0.0004876562729317932
Epoch 900, Avg Epoch Cost: 0.000425304595729487
Total Cost is 11505.502828956784
Epoch 999, Avg Total Cost: 0.07670335219304522
